name: build

on:
  workflow_dispatch:


permissions:
  actions: read
  contents: write
  id-token: write
  security-events: write

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v3
        name: install dotnet
        with:
          dotnet-version: |
            8.0
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: nuget/setup-nuget@v1
        name: install nuget
        with:
          nuget-api-key: ${{ secrets.GITHUB_TOKEN }}

      - uses: carlosperate/arm-none-eabi-gcc-action@v1

      - name: build native
        run: chmod a+x build.sh && ./build.sh

      - name: build csharp
        run: dotnet build -r .