name: build

on:
  workflow_dispatch:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions:
  actions: read
  contents: write
  id-token: write
  security-events: write

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v3
        name: install dotnet
        with:
          dotnet-version: |
            8.0
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: nuget/setup-nuget@v1
        name: install nuget
        with:
          nuget-api-key: ${{ secrets.GITHUB_TOKEN }}

      - name: build csharp
        run: dotnet build -p:Configuration=Release -p:Version:1.0.0.${{ vars.GITHUB_RUN_NUMBER }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: bindings
          path: |
            packages/csharp/**/*.nupkg
          if-no-files-found: error

      - name: publish nuget pkg
        run: |
          find -type f | grep nupkg$ | grep -v 'symbols\.nupkg$' | while read line; do
            echo "Pulish: $line"
            nuget push $line \
              -Source https://api.nuget.org/v3/index.json \
              -ApiKey ${{ secrets.NUGET_TOKEN }} \
              -SkipDuplicate
          done